/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as FoodMarketRouteImport } from './routes/food-market'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as BecomeAVendorRouteImport } from './routes/become-a-vendor'
import { Route as BecomeASponsorRouteImport } from './routes/become-a-sponsor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodMarketRoute = FoodMarketRouteImport.update({
  id: '/food-market',
  path: '/food-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAVendorRoute = BecomeAVendorRouteImport.update({
  id: '/become-a-vendor',
  path: '/become-a-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeASponsorRoute = BecomeASponsorRouteImport.update({
  id: '/become-a-sponsor',
  path: '/become-a-sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-sponsor': typeof BecomeASponsorRoute
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/experiences': typeof ExperiencesRoute
  '/food-market': typeof FoodMarketRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-sponsor': typeof BecomeASponsorRoute
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/experiences': typeof ExperiencesRoute
  '/food-market': typeof FoodMarketRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-sponsor': typeof BecomeASponsorRoute
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/experiences': typeof ExperiencesRoute
  '/food-market': typeof FoodMarketRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-sponsor'
    | '/become-a-vendor'
    | '/experiences'
    | '/food-market'
    | '/schedule'
    | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-sponsor'
    | '/become-a-vendor'
    | '/experiences'
    | '/food-market'
    | '/schedule'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-a-sponsor'
    | '/become-a-vendor'
    | '/experiences'
    | '/food-market'
    | '/schedule'
    | '/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeASponsorRoute: typeof BecomeASponsorRoute
  BecomeAVendorRoute: typeof BecomeAVendorRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FoodMarketRoute: typeof FoodMarketRoute
  ScheduleRoute: typeof ScheduleRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-market': {
      id: '/food-market'
      path: '/food-market'
      fullPath: '/food-market'
      preLoaderRoute: typeof FoodMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-vendor': {
      id: '/become-a-vendor'
      path: '/become-a-vendor'
      fullPath: '/become-a-vendor'
      preLoaderRoute: typeof BecomeAVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-sponsor': {
      id: '/become-a-sponsor'
      path: '/become-a-sponsor'
      fullPath: '/become-a-sponsor'
      preLoaderRoute: typeof BecomeASponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeASponsorRoute: BecomeASponsorRoute,
  BecomeAVendorRoute: BecomeAVendorRoute,
  ExperiencesRoute: ExperiencesRoute,
  FoodMarketRoute: FoodMarketRoute,
  ScheduleRoute: ScheduleRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
